# Numpy (Day-3)

## Indexing and Slicing

In [1]:
import numpy as np

In [3]:
# Creating a numpy array 
arr1 = np.array([1, 2, 3, 4, 5,6,7])
print(arr1)

[1 2 3 4 5 6 7]


In [42]:
print(arr1[1])
print(arr1[0])
print(arr1[0:])
print(arr1[:-1])
print(arr1[:])
print(arr1[-5:-1])
print(arr1[(arr1>2) &( arr1<5)])
print(arr1[(arr1>2) | ( arr1<5)])

2
1
[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7]
[3 4 5 6]
[3 4]
[1 2 3 4 5 6 7]


In [ ]:
arr2 = np.arange(0,12,2)
print(arr2)
print('---------------------')
print(arr2[1])
print(arr2[0])
print(arr2[0:])
print(arr2[:-1])
print(arr2[:])
print(arr2[-5:-1])

[ 0  2  4  6  8 10]
---------------------
2
0
[ 0  2  4  6  8 10]
[0 2 4 6 8]
[ 0  2  4  6  8 10]
[2 4 6 8]


In [39]:
len(arr2)
arr2.size
arr2.ndim

arr2_re = arr2.reshape(2,3)
print(arr2_re)
print('----------')
print(arr2_re[0])
print('----------')
print(arr2_re[1])

[[ 0  2  4]
 [ 6  8 10]]
----------
[0 2 4]
----------
[ 6  8 10]
