# Numpy (Day-2)

In [1]:
import numpy as np

In [2]:
empty = np.empty((4,5))
print(empty)
empty[0]

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 8.01092456e-307
  1.11261095e-306]
 [1.37961302e-306 1.05699242e-307 1.95821439e-306 2.22522597e-306
  1.33511969e-306]
 [7.56593017e-307 8.01097889e-307 1.78020169e-306 7.56601165e-307
  1.02359984e-306]
 [1.33510679e-306 2.22522597e-306 2.22523140e-306 1.02360867e-306
  1.06811422e-306]]


array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 8.01092456e-307,
       1.11261095e-306])

In [3]:
# Rang array 
range_array = np.arange(6)
range_array

array([0, 1, 2, 3, 4, 5])

In [4]:
# Array of even numbers 
even = np.arange(0,12,2)
even

array([ 0,  2,  4,  6,  8, 10])

In [5]:
# Array of odd numbers
odd = np.arange(1,14,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13])

In [6]:
# Array with specific difference
# dif_three = np.arange(0,15,0.55)
# dif_three = np.arange(0,15,3)
# dif_three = np.arange(0,15,0.7)
dif_three = np.arange(0,15,6)
dif_three

array([ 0,  6, 12])

- You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [7]:
lin = np.linspace(0,12,num=10)
lin = np.linspace(0,12,num=6)   
lin = np.linspace(0,20,num=10)   
lin = np.linspace(0,60,num=5)   
print(lin.dtype)
lin

float64


array([ 0., 15., 30., 45., 60.])

- Specifying your data type

   - While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [8]:
lin = np.linspace(0,70,num=20 ,dtype=np.int64)   
print(lin.dtype)
lin

int64


array([ 0,  3,  7, 11, 14, 18, 22, 25, 29, 33, 36, 40, 44, 47, 51, 55, 58,
       62, 66, 70])

In [9]:
lin = np.linspace(0,70,num=20 ,dtype=np.float64)   
print(lin.dtype)
lin

float64


array([ 0.        ,  3.68421053,  7.36842105, 11.05263158, 14.73684211,
       18.42105263, 22.10526316, 25.78947368, 29.47368421, 33.15789474,
       36.84210526, 40.52631579, 44.21052632, 47.89473684, 51.57894737,
       55.26315789, 58.94736842, 62.63157895, 66.31578947, 70.        ])

- Sorting an array is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [10]:
# Creating a array with random numbers 1-20
Rarr = np.array((1,99,33,65,77,22,44,33,9,88))
print(Rarr)
print(np.sort(Rarr))

[ 1 99 33 65 77 22 44 33  9 88]
[ 1  9 22 33 33 44 65 77 88 99]


In [11]:
# Create a sample array
arr_2d = np.array([[0, 3], [2, 2]])
print(arr_2d)
# Output:
# array([[0, 3],
#        [2, 2]])
print('-----------')
# Get the indices that would sort the array along the first axis
ind = np.argsort(arr_2d, axis=0)
print(ind)
# Output:
# array([[0, 1],
#        [1, 0]])
print('-----------')
# Sort the array along the first axis using the indices
sorted_arr_2d = np.take_along_axis(arr_2d, ind, axis=0)
print(sorted_arr_2d)
# Output:
# array([[0, 2],
#        [2, 3]])


[[0 3]
 [2 2]]
-----------
[[0 1]
 [1 0]]
-----------
[[0 2]
 [2 3]]


- You can concatenate them with `np.concatenate()`

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a)
print(b)
np.concatenate((a, b))

[1 2 3 4]
[5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
arr_2d_1 = np.array([[1, 2], [3, 4]]) # 2x2 array
arr_2d_2 = np.array([[5, 6]]) # 1x2 array
print(arr_2d_1) , print('-----------')
print(arr_2d_2) , print('-----------')

# Concatenate 2D arrays
arr_2d_conc = np.concatenate((arr_2d_1, arr_2d_2), axis=0)
arr_2d_conc

[[1 2]
 [3 4]]
-----------
[[5 6]]
-----------


array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
arr_2d_1 = np.array([[1, 2], [3, 4]]) # 2x2 array
arr_2d_3 = np.array([[5,1], [7, 1]]) # 2x2 array
print(arr_2d_1) ,print('-------')
print(arr_2d_3) ,print('-------')

[[1 2]
 [3 4]]
-------
[[5 1]
 [7 1]]
-------


(None, None)

In [15]:
np.concatenate((arr_2d_1, arr_2d_3) , axis=1)


array([[1, 2, 5, 1],
       [3, 4, 7, 1]])

- Let's create a 3D array

In [16]:
arr_3d_1 = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
arr_3d_1

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

- `arr_3d_1.ndim` will tell you the number of axes, or dimensions, of the array.

In [17]:
# To find the number of dimensions of the array, run:
arr_3d_1.ndim

3

- `arr_3d_1.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.



In [18]:
#To find the total number of elements in the array, run:
arr_3d_1.size

24

- `arr_3d_1.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [19]:
# And to find the shape of your array, run:
arr_3d_1.shape

(3, 2, 4)

 ## Can we reshape an array?
- Yes!

  - Using `arr.reshape()` will give a new shape to an array without changing the data. Just remember that when we use the reshape method, the array we want to produce needs to have the same number of elements as the original array. If we start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [20]:
arr_r = np.arange(8)
arr_r

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
#  We can use `reshape()` to reshape your array. For example, you can reshape this array to an array with three rows and two columns:
arr_reshap1 = arr_r.reshape((4,2))
arr_reshap1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [22]:
# With np.reshape, you can specify a few optional parameters:

np.reshape(arr_r, shape=(2,4), order='C')

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### How to Convert a 1D Array into a 2D Array (How to Add a New Axis to an Array) 
- we can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array. Using `np.newaxis` will increase the dimensions of our array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [23]:
a = np.array([1, 2, 3, 4, 5, 6])

- You can use `np.newaxis` to add a new axis

In [29]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[1 2 3 4 5 6]]


(1, 6)

 - Or, for a column vector, you can insert an axis along the second dimension:

In [27]:
col_vector = a[:, np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

## Indexing and slicing
### You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [65]:
data = np.array([1, 2, 3])
print(data)
print(data[0]) # Output: 1
print(data[1]) # Output: 2
print(data[2]) # Output: 3
print(data[0:2]) # 0:2 means from index 0 to 1 (not 2)
print(data[0:3])  # 0:3 means from index 0 to 2 (not 3)
print(data[-1]) # -1 means the last element
print(data[0:]) # 0: means from index 0 to the end
print(data[-3:-1]) # -3:-1 means from the third last element to the second last element

[1 2 3]
1
2
3
[1 2]
[1 2 3]
3
[1 2 3]
[1 2]


In [ ]:
no_data = np.array([1,2,3,4,90,5,6,7,8,9,10,11,12,15,16,17,18,19,20])
print(no_data)
print(np.sort(no_data)) # sort the array in ascending order
print(no_data[no_data < 10]) # no_data < 10 means from index 0 to 9 (not 10) 

five_up = (no_data >= 5) # no_data >= 5 means from index 5 and above 5 (= means 5 included)
print(no_data[five_up]) 

[ 1  2  3  4 90  5  6  7  8  9 10 11 12 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 15 16 17 18 19 20 90]
[1 2 3 4 5 6 7 8 9]
[90  5  6  7  8  9 10 11 12 15 16 17 18 19 20]


In [121]:
data_2d  =np.array([[1,2,3,4,5] , [6,7,8,9,10] ,[11,12,13,14,15]])
print(data_2d) , print('-------------------')
print(data_2d[0]) # prints the first row 
print('-------------------')
print(data_2d[1])
print('-------------------')
print(data_2d[data_2d < 5]) # prints all elements less than 5
print(data_2d[data_2d < 6]) # prints all elements less than 6
print(data_2d[data_2d < 7]) # prints all elements less than 7
print('-------------------')
print(data_2d[data_2d > 3]) # prints all elements greater than 3
print(data_2d[data_2d > 6]) # prints all elements greater than 6


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-------------------
[1 2 3 4 5]
-------------------
[ 6  7  8  9 10]
-------------------
[1 2 3 4]
[1 2 3 4 5]
[1 2 3 4 5 6]
-------------------
[ 4  5  6  7  8  9 10 11 12 13 14 15]
[ 7  8  9 10 11 12 13 14 15]


In [ ]:
# Filter even numbers
even_numbers = data_2d[data_2d%2 == 0] 
even_numbers 


array([ 2,  4,  6,  8, 10])

In [103]:
# Filter odd numbers
odd_numbers = data_2d[data_2d%2 == 1] 
odd_numbers 

array([1, 3, 5, 7, 9])

In [126]:
# Use to condition
print(data_2d[(data_2d > 3) & (data_2d < 13) & (data_2d % 2 == 0)])  # returns all the divisor of 2  btw 3 and 13
print(data_2d[(data_2d > 3) & (data_2d < 13) & (data_2d % 2 == 1)])  # returns all the number which are not the divisor of 2  btw 3 and 13

[ 4  6  8 10 12]
[ 5  7  9 11]


In [131]:

print(data_2d[(data_2d < 3) & (data_2d < 13)])
print('----------') 
# | is the the (or) in programming
print(data_2d[(data_2d < 3) | (data_2d < 13)]) 

[1 2]
----------
[ 1  2  3  4  5  6  7  8  9 10 11 12]
