# Numpy (Day-5)

In [8]:
import pandas as pd
import numpy as np

- Matrix or Matrices 

In [9]:
# Create a 2x3 matrix in numpya
arr = np.array([[1, 2 , 3], [ 4,5,6] ])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# create a matrix of big dimension 
a = np.arange(0, 100 , 2).reshape(5,10)
print(a)


[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [37]:
# slicing a matrix 
a[   1:3   ,    3:5   ]
#   rows      columns    

array([[26, 28],
       [46, 48]])

In [ ]:
#  maximum elements in matrix 
print(a.max())


98


array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [42]:
#  minimum elements in matrix 
print(a.min())

0


In [41]:
# Sum of matix 
print(a.sum())

2450


In [45]:
a

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [49]:
print(a.max(axis=0)) # only for columns
print(a.max(axis=1)) # only for rows

[80 82 84 86 88 90 92 94 96 98]
[18 38 58 78 98]


In [50]:
print(a.min(axis=0)) # only for columns
print(a.min(axis=1)) # only for rows

[ 0  2  4  6  8 10 12 14 16 18]
[ 0 20 40 60 80]


In [54]:
b = np.arange(0,20,2).reshape(5,2)
b

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [77]:
# to add a row in matrix 
c = np.array([4,6])
b = np.vstack((b, c))
b

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [ 4,  6]])

In [78]:
np.flip(b)

array([[ 6,  4],
       [18, 16],
       [14, 12],
       [10,  8],
       [ 6,  4],
       [ 2,  0]])